spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chatdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

jwt:
  # kimbanseokTokenkimbanseokTokenkimbanseokToken
  # BASE64 인코딩
  secretKey: a2ltYmFuc2Vva1Rva2Vua2ltYmFuc2Vva1Rva2Vua2ltYmFuc2Vva1Rva2Vu
  expiration : 3000
